# Generated by Django 6.0.2 on 2026-07-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Bolsista',
                'verbose_name_plural': 'Bolsistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(auto_now_add=True, verbose_name='Entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('min_trabalhados', models.IntegerField(blank=True, null=True, verbose_name='Minutos Trabalhados')),
                ('diferenca_min', models.IntegerField(blank=True, null=True, verbose_name='Diferença (min)')),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bolsista', verbose_name='Bolsista')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-entrada'],
            },
        ),
    ]
