# Generated by Django 6.0.2 on 2026-07-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='pendencia_min',
            field=models.IntegerField(default=0, verbose_name='Pendência (min)'),
        ),
        migrations.AddField(
            model_name='sessaotrabalho',
            name='pendencia_abatida_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pendência abatida (min)'),
        ),
    ]
