# Generated by Django 6.0.2 on 2026-07-15 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bolsista_pendencia_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaotrabalho',
            name='entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entrada'),
        ),
    ]
