# Generated by Django 6.0.2 on 2026-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sessaotrabalho_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaotrabalho',
            name='entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entrada'),
        ),
    ]
