# Generated by Django 6.0.2 on 2026-08-24 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sessaotrabalho_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaotrabalho',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('pendencia', 'Pagamento de pendência')], default='normal', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sessaotrabalho',
            name='entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entrada'),
        ),
    ]
