# Generated by Django 6.0.2 on 2026-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sessaotrabalho_tipo_alter_sessaotrabalho_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Token de acesso'),
        ),
    ]
