# Generated by Django 6.0.2 on 2026-08-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_popula_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token de acesso'),
        ),
    ]
