# Generated by Django 6.0.2 on 2026-09-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bolsista_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaotrabalho',
            name='abandonada',
            field=models.BooleanField(default=False, verbose_name='Abandonada'),
        ),
    ]
